---
title: "Lithium: From Natural Element to Bipolar Disorder Treatment"
date: "2024-05-14"
categories: [biology, popular science, epistemology, drug discovery, mental health, EN]
bibliography: my-refs.bib
description: This post describes the discovery of lithium as a treatment for BD.
---

::: {.callout-note}
This essay was a project of one of the [R3](https://publichealth.jhu.edu/the-r3-center-for-innovation-in-science-education/programs/r3-courses-for-graduate-students-at-the-bloomberg-school-and-johns-hopkins-university) class series I took. Please **do not** consider it as medical advice. 
:::

The records of using lithium as a treatment for bipolar disorder (BD), once called ‘manic-depressive illness’ in a descriptive way, were rather short, even though the history of BD can be traced back to antiquity. BD patients suffer from non-stop cycles of emotional highs and lows, and if left untreated, the suicide rates of BD patients are 10-20 times higher than the general population [@Draaisma2019LithiumHistory]. Since the discovery of its therapeutic usage in 1949 and its U.S. FDA approval for the treatment of mania in 1970 [@Halford2013LithiumDrug], oral tablets of lithium carbonate (a common lithium salt) remain the standard treatment method for mania today, despite many other drugs have been used in mental diseases treatment over the years [@Wen2019LithiumReview].

## A History of Lithium

Of all the psychiatric drugs available today, a notable feature of lithium is that it is a naturally occurring element rather than synthesized chemicals (e.g., CPZ for schizophrenia treatment). Discovered by J. A. Arfvedson in 1817 as an alkali metal during mineral petalite analysis, lithium was first introduced to the medical field in 1859 as a treatment of gout (a disease in which patients accumulate urate crystals in their joints) by Alfred Barring Garrod due to its ability to dissolve urate stones [@Ban2006Serendipity]. Early implementation of lithium in psychiatric diseases treatment was based on the popular assumption in 19th century, that ‘uric acid diatheses’ could lead to a series of symptoms ranging from gout to mental illness, but due to lack of technologies to monitor blood levels in patients, lithium treatment was abandoned due to its toxicity [@Ban2006Serendipity]. 

## John Cade, the Untrained Psychiatrist Who Re-discovers Lithium’s Treatment Effects

The re-discovery of lithium’s treatment effects in mania was not made possible until the 1940s. The Australian psychiatrist John Cade, retired from World War II, set up a largely amateur laboratory in the woodsheds of the hospital he worked in in rural Australia. Based on the assumption that ‘mania-depressive illness’ is analogous to thyrotoxicosis and myxedema – that one state of the illness can be attributed to the excess of one substance in the body and the other state can be attributed to the lack of the same substance, Cade wanted to find the excess substance in mania patients. The psychiatrist injected urine collected from mania patients and normal people into the abdominal compartments of guinea pigs and found the former was more toxic in killing animals. He therefore decided to test the uric acid’s toxicity in guinea pigs and happened to use lithium urate – the most soluble form of urate – in his experiments. 

To his astonishment, lithium urate protected the animals from dying compared to pure urea solution, and he subsequently found that injection of lithium carbonate aqueous solution can make guinea pigs lethargic and unresponsive to stimuli for a long period. Cade therefore tried to apply lithium as a treatment for manic, depressed, and schizophrenic patients and found its effects most evident in manic patients [@Ban2006Serendipity]. Cade’s early conclusions were re-investigated and confirmed by Mogens Schou’s clinical investigations in the 1950s in Denmark, followed by the discovery of its prophylactic effects in BD and recurrent depression. 

Since the 1960s, when blood pressure level measurement was made possible by the employment of a flame spectrophotometer, lithium has been widely applied in BD treatment ever since [@Ban2006Serendipity]. At the time of treating psychiatric diseases by electroconvulsive therapy (introducing seizures electrically) and lobotomy (severing the connections of patients’ prefrontal cortex), lithium was the first effective medication available to significantly alleviate the symptoms of a mental illness. 

## A Story of Serendipity that is Problematic under Modern Research Standards

The re-discovery of lithium’s treatment effects by John Cade was largely portrayed as a story of serendipity – a story where a false hypothesis or theory leads to an empirically correct conclusion [@Ban2006Serendipity]. The U.S. psychiatrist Walter A. Brown believes that a systematic process might be at play behind the myth of ‘lucky discovery by an amateur scientist’. In his book Lithium: A Doctor, a Drug, and a Breakthrough [@Brown2019Lithium], Brown points out that the discovery of lithium’s drug effect is a paradox, where Cade’s experiments were problematic regarding hypothesis, sample storage, observed effects (the guinea pigs may be intoxicated to appear ‘sedated’), and research ethics – such research would not be approved by modern research institutions, but its discovery was indeed distinctive. It has reshaped people’s view of mental illnesses as treatable diseases and saved millions of lives ever since.
