---
title: "日记 | 黑狗"
date: "2025-03-20"
categories: [diary, 中文]
---

最近又处在僵死期，正在很努力地复健。不能让形而上的恐慌夺走我真正生活的能力。并且我也得明白，哪些是真正对我好的娱乐，哪些只是一时的消遣。

| good for my soul                         | junk food                              |
|------------------------------------------|----------------------------------------|
| 音乐与诗歌，好的歌词就是诗               | 视奸社交媒体                           |
| 小说和哲学                               | 键政                                   |
| 画画，不局限于同人作品                   | Wikipedia diving                       |
| 与真实的人类在线下真诚的相处、交流、约会 | 吃垃圾食品 + body negative thoughts    |
| 新鲜空气，大海，鸟鸣，树木               | 不起床，靠睡觉消磨时间、逃避现实       |
| 乐观心态，从心所欲，少纠结               | 在行动前因为自己不可控的因素纠结个不停 |

世界的确是在往更差劲的方向发展，我们都明白。这5年对于我来说就仿佛凝滞了一般，我也明白。在一切天真的乐观主义都不能够再将我蒙蔽的时刻——每次再次抬起头面对现实，都会因为伤口再次撕开而感到更加新鲜火辣的疼痛，而这个疼痛的程度在我试图掩盖时只会不断加深而不是愈合——想要继续相信未来，就需要发展出一种全新的乐观主义，而我觉得这种乐观主义不是靠翻书能找到的。我必须勇敢坚强地生活，需要去感受当下时代的脉搏，在那之中寻找我能所珍视的东西，而不是在脑海内部构建理想国；因为后者只会让人身心俱疲，以至于导向自杀冲动。需要和心理医生多聊聊。对自己诚实。如果感觉把自己内心的想法告诉别人会紧张，就多和日记聊聊。现代生活是垃圾，当代生活更是，但你还有有志做艺术家的，不是吗？把不满收集起来，发泄出来，用一种内敛真诚的表达方式；不能屈从于你不喜欢的社会架构和主流风潮，也不能被他们打败。遵从本性生活，以个人的头脑作为最小的武装单位发起抗争吧。

> 停电之后，暂时摆脱了/坚硬的时刻，倒转的河/肥胖的城市，驱赶着所有拒绝沉默的人

------------------------------------------------------------------------

复健成功了一半，至少可以这么说。我猜以后自己得学着怎么一辈子和这只黑狗做斗争了——“斗争”是个坏词儿——学着怎么一辈子和这只黑狗相处。身体是革命的本钱，我们一元论者把心理健康也算成身体的一部分。体会自己的情感和需求，就像驾驶EVA一样驾驶自己的肉身，像驯服一条烈马一样驯服自己。其实EVA的比喻很有启发性，如果同步率下降了的话，再怎么希望机器启动也是不会成功的，只有把自己的需求当成第一步才行。

以后几个需要警觉的坏信号：睡眠周期紊乱，无法专注30分钟以上，食欲不振，早晨醒来后很不想出门，感觉不到快乐和对未来的期待，自杀冲动。这种事的发生证明了你是要休息，而不是“你真糟糕”。
