---
title: "Stat4Bio | 3. Estimation and Confidence"
date: "2026-03-13"
categories: [statistics, notes, estimation, confidence, draft, EN]
---

## Probability

When random sampling, we're indeed interested in the distribution of measurements in the underlying (possibly hypothetical) population. 
When we make n independent measurements, we have X_1,X_2,X_3,…,X_n  iids, following the population distribution. 

Population mean μ: 
	a parameter, fixed quantity, unknown (we want to know)
Sample mean X ̅: 
	an estimator of μ, random quantity, a function of the data (X)
Observed sample mean x ̅: 
	an estimate of μ, a particular realization of the estimator  X ̅, a fixed quantity but the result of a random process.
Similarly, population SD σ and sample SD S, …


Sampling Distribution
Dependent on type of statistic, population distribution, and the sample size.

Example:

Considering a parameter θ and its estimator θ ̂…
	• Bias: E(θ ̂−θ)=E(θ ̂ )−θ
	• Standard Error: SE(θ ̂ )=SD(θ ̂ )
	• RMS Error (RMSE): √(E{(θ ̂−θ)^2 } )=√((bias)^2+(SE)^2 )
	
Assume X_1,X_2,X_3,…,X_n  are iid with mean μ and SD σ.
	• Mean of X ̅=E(X ̅ )=μ
	• Bias = E(X ̅ )−μ=0
	• SE of X ̅=SD(X ̅ )=σ/(√n)
	• RMSE of X ̅=√((bias)^2+(SE)^2 )=(σ\ )/(√n)

If the population is normally distributed
If X_1,X_2,X_3,…,X_n  are iid, the population is Normal(μ,σ), 
then the distribution of sample mean would be X ̅~Normal(μ,σ/(√n))


Central Limit Theorem: 
If X_1,X_2,X_3,…,X_n  are iid with mean μ and SD σ, and the sample size is large, then the distribution of sample mean would be X ̅~Normal(μ,σ/(√n))

The Sample SD
S=√((∑(X_i−X ̅ )^2)/(n−1))

If {X_i} are iid, with mean μ and SD σ, then
	• E(S^2 )=σ^2
	• E{(n−1)/n S^2 }=(n−1)/n σ^2<σ^2
In other words…
	• Bias(S^2 )=0
	• Bias((n−1)/n S^2 )=(n−1)/n σ^2−σ^2=−1/n σ^2

The Distribution of the Sample SD
If X_1,X_2,X_3,…,X_n  are iid Normal(μ,σ), then the sample SD S satisfies ((n−1) S^2)/σ^2 ~X_(n−1)^2
	• Note: n-1 degree of freedom (df)



Recap: Sample Mean
If X_1,…,X_n  have mean μ and SD σ, then
	• E(X ̅ )=μ nomatter what
	• SD(X ̅ )=σ/(√n)  if the X's are independent

If X_1,…,X_n  are iid normal (mean = μ, SD = σ), then
X ̅~Normal(mean= μ, SD=σ/(√n))

If X_1,…,X_n  are iid with mean μ and SD σ and the sample size n is large, then
X ̅~Normal(mean= μ, SD=σ/(√n))


What is Confidence Interval (CI)?
If X_1,…,X_n  are iid normal (mean = μ, SD = σ), and σ is known. 
X ̅  ~ Normal(mean= μ, SD=σ/(√n))
	- we know σ but not μ. So we assume normal. 
	
So, how close is X ̅  to μ?

For a standard normal distribution, Pr(-1.96<Z<1.96) = 0.95. i.e., there's 95% probability that a standard normal variable Z will fall between -1.96 and 1.96. 

Pr⁡(−1.96≤(X ̅−μ)/(σ/√n)≤1.96)=95%
Pr⁡(X ̅−1.96σ/√n≤μ≤X ̅+1.96σ/√n)=95%

	That is sample mean ± Z value * SD. 
In advance, X ̅±1.96σ/√n  has a 95% chance of covering μ (the population parameter). That is called a 95% confidence interval. 

90%/99% confidence -> shorter/longer intervals


What if we don't know the population SD σ?
We would plug in the sample SD S, but we need to widen the intervals to account for the uncertainty in S. 
-> Student t distribution. 

If X_1,…,X_n  are iid normal (mean = μ, SD = σ),
(X ̅−μ)/(S/√n)  ~ t(df=n−1)
X ̅±t(α/2,n−1)S/√n  is a 1-α confidence interval for μ.
	-> t(α/2,n−1): the 1-α/2 quantile of the t distribution with n-1 df; a = 5% (for 95% CI).


R code:
qt(0.975, 9) # calculate x when P(x)=0.975 (two-sided for 95% CI), df=9
pt(1.96, 9) # calculate P(x) when x=1.96 (95% CI), df=9


Two Sets of Data
Difference between Means (X ̅−Y ̅)
If X_1,…,X_n  are iid normal (mean = μ_A, SD = σ), and Y_1,…,Y_m  are iid normal (mean = μ_B, SD = σ)…
Then, 
E(X ̅−Y ̅ )=E(X ̅ )−E(Y ̅ )=μ_A−μ_B
SD(X ̅−Y ̅ )=√(SD(X ̅ )^2−SD(Y ̅ )^2 )=√((σ/√n)^2−(σ/√m)^2 )=σ√(1/n+1/m)
Note: if n=m, then SD(X ̅−Y ̅ )=σ√(2/n).

Pooled Estimate of the Population SD σ ̂_pooled
σ ̂_A=S_A=√(∑▒(X_i−X ̅ ) ^2/(n−1)), σ ̂_B=S_B=√(∑▒(Y_i−X ̅ ) ^2/(m−1))
σ ̂_pooled=√((∑▒〖(X_i−X ̅ )^2+∑▒(Y_i−Y ̅ ) ^2 〗)/(n+m−2))= √((S_A^2 (n−1)+S_B^2 (m−1))/(n+m−2))
Note: if n=m, then σ ̂_pooled=√((S_A^2+S_B^2)/2).

Estimated SE of (X ̅−Y ̅)
(SD) ̂(X ̅−Y ̅ )= σ ̂_pooled √(1/n+1/m)=√([(S_A^2 (n−1)+S_B^2 (m−1))/(n+m−2)]⋅[1/n+1/m]).
Note: if n=m, then (SD) ̂(X ̅−Y ̅ )=√((〖S_A^2+S〗_B^2)/n).

CI for the Difference between the Means
((X ̅−Y ̅ )−(μ_A−μ_B))/( (SD) ̂(X ̅−Y ̅ ) )  ~ t(df=n+m−2)
To calculate this…
	1. Calculate (X ̅−Y ̅ )
	2. Calculate (SD) ̂(X ̅−Y ̅ )
	3. Find the 97.5 percentile of the t distribution with n+m-2 df. -> t value
	4. Calculate the interval: (X ̅−Y ̅ )±t⋅(SD) ̂(X ̅−Y ̅ ).

What if… the two populations really have different SDs, σ_A  and σ_B?
Then ((X ̅−Y ̅ )−(μ_A−μ_B))/( (SD) ̂(X ̅−Y ̅ ) )  would not follow a t distribution. 

Then we use an approximation - 
Let k = 

Let t* be the 97.5 percentile of the t distribution with k df.
-> use (X ̅−Y ̅ )±t^∗ (SD) ̂(X ̅−Y ̅ )  as a 95% confidence interval. 


Confidence Interval for the Population SD: chi-square (χ^2 )  distribution. 
((n−1) S^2)/σ^2 ~χ^2 (df=n−1)


Choose L & U such that Pr⁡(L≤((n−1) S^2)/σ^2 ≤U)=95%.
-> (S√((n−1)/U), S√((n−1)/L)) is the 95% CI for σ.
