---
title: "观后感 | 一切皆被慈爱的机器所注视"
date: "2024-04-01"
categories: [review, documentary, 中文]
---

> I like to think (and the sooner the better!) of a cybernetic meadow
>
> where mammals and computers live together in mutually programming harmony
>
> like pure water touching clear sky.
>
> [*“All Watched Over by Machines of Loving Grace” by Richard Brautigan*](https://allpoetry.com/All-Watched-Over-By-Machines-Of-Loving-Grace)

这部纪录片的标题来源于这首作于嬉皮年代的小诗。在生活在当代的导演看来，应当是绝佳的讽刺吧。

## 观后感

### Episode 1：Love & Power

这一集讲述的是上世纪颇有影响力的哲学家Ayn Rand，和新自由主义/加州精英主义（相信只要所有人都能做到极度的理性/自私——和电脑一样理性/自私——就可以创造一个全新的、民主的平衡世界）之间的关系。导演试图说明这个电脑+Ayn Rand创造的“人们可以通过个人主义和理性主义来调控世界的乌托邦”是不存在的——在个人层面上，聚集在Ayn周围的小群体因为Ayn与其中一位成员的关系而终结了；在大的层面上，这种蔓延至美国领导层的坚信导致了97年左右的亚洲金融危机和09年左右的世界金融危机。

个人的观后感是这一集的联系有点牵强，或者说偏执。我很不喜欢的一点就是把Ayn的陨落简单地归于爱情的失败，用一种“爱情一定是非理性的”的态度来攻击她的理性主义。是不是有点太狡猾了呢？看到女人就觉得爱情一定是最终把她击败的困境。我总觉得攻击一个哲学家应该用另一套哲学理论来攻击，而不是用她“没能live up to her philosophy”来攻击，这样的话可以攻击的哲学家多了去了。

### Episode 2: The Use and Abuse of Vegetational Concepts

这一集讲述的是“世界是一个趋向于平衡（equilibrium）的系统”这个概念是如何被发明和滥用的。导演首先提出了一个概念：生态系统是一个稳定的系统。很熟悉吧？大家都是这么想的。但追溯历史的脉络，我们发现这个概念其实并不是经过严谨的科学实验证实的事实，而是最早的生态学家出于对电脑模型的痴迷、以及一种古老的哲学执念而创造的一个过于简化的模型。事实是不是这样呢？这个概念被发明的五十年后，新一代的生态学家用数据、实验和建模将其驳倒了。

但可惜的是，导演认为这样的概念已经深深地潜入了大众的心中。这导致了两个后果：1）大家过于相信“人可以通过点对点的连接组成一个能自我平衡的系统，不需要任何权威/权力结构的维持”这个概念，却不知这是不可能长久的。这里有讲美国70年代嬉皮士们失败的family commune尝试（我觉得就是他们重新“发现”了《利维坦》——无组织终将导向混乱，所以每个人必须上交权力给暴力机构以维持必要的稳定状态），21世纪通过互联网连结而发动的没有领导者的革命，等等。2）政治家滥用这个概念用于维护统治者的权威。“世界是一个平衡的系统，所以政治家要做的仅仅是维持目前的状态”，这种观念让启蒙年代的进步主义消失了，取而代之的是一种大家不知道该往哪里前进的虚无状态。

这是我最喜欢的一集，可能因为正好和我的专业内容联系比较紧密吧。并且我处于一种常年的虚无主义漩涡中，所以被这么激一下也挺好的。

### Episode 3: The Monkey in the Machine and the Machine in the Monkey

*警告：尸体/战争场景呈现*

这一集讲述的是“自私的基因”理论（创造者是两位科学家Price和Hamilton），上世纪白人精英主义对于改变世界的梦想，那位研究山地大猩猩的科学家Fossey，电脑的发明对世界的影响，以及刚果内战之间的联系。导演试图说明将人类机器化的、极度理性的“自私的基因”理论（即人类的行为，无论是好的还是坏的，实际上都是由存在于我们之上的机器——即我们的DNA组成的巨大计算系统——所控制的，并且一切都为且仅为基因的存续而存在）实际上导致了荒谬且自相矛盾的后果。Price因为害怕自己理论的结论而成为了基督徒与布道者，但却导致了更多的伤害；Hamilton成为了极端的进化论信奉者——反对现代医学，因为会让弱者的基因存续下去；Fossey为了大猩猩的福祉恐吓当地人民，最终死在营地里；由比利时自由主义者发起的刚果民主化进程最终导致了惨无人道的刚果内战。

这是我感觉最令人震撼的一集。把很多略有耳闻的事件相互串联，加上导演高超的剪辑手法，达到了可以说是mind-blowing的效果。人类的存在真是荒谬啊。下辈子让我当水母吧！这辈子就当个人文主义者。

### 整体观感

导演的剪辑功力非常强，喜欢用庵野秀明式的“为残忍的画面配上纯净的音乐，为美丽的画面配上悬疑的音乐”手法来制造紧张气氛；第三集开头的一段剪辑简直可以称为吗喽罗曼史，非常震撼，猴核爱好者的必看教材。如果我在大一就看了这个我的期末电影作业也不会拿B-了。

导演喜欢用全知全能的视角在一个小时里串联起几十年间似乎没有关系的一些事件以讲述道理。我个人觉得这个形式震撼力很强，但有时解释不够，反而让人对他试图证明的理论产生些微怀疑。

价值观上，我觉得导演是个进步/启蒙主义复兴者。对解决人在现代生活中常有的虚无感，增加一点自信心挺好的；但对于一些理科概念的解释就略有点牵强附会。

但绝对不是无聊的片子，质量还是非常高的。大家都可以去看看！

------------------------------------------------------------------------

### 资源

#### Vimeo

[Episode1: “Love and Power”](https://vimeo.com/515004292)

[Episode2: "The Use and Abuse of Vegetational Concepts"](https://vimeo.com/529013583)

[Episode3: "The Monkey in the Machine and the Machine in the Monkey"](https://vimeo.com/541217333)

#### Wikipedia

相当于是文字版的纪录片。

[All Watched Over by Machines of Loving Grace (TV series)](https://en.wikipedia.org/wiki/All_Watched_Over_by_Machines_of_Loving_Grace_(TV_series))

至于我为什么会想到看这个纪录片？

是因为ride的新歌[Essaouira](https://www.youtube.com/watch?v=YbpaV8e5EKQ)的歌词…感谢Mark Gardener一如既往的掉书袋习惯（和我一如既往的考据党习惯）。
