---
title: "Stat4Bio | 0. Experimental Design"
date: "2026-01-10"
categories: [stat4bio, statistics, notes, biology, experimental design, EN]
description: This page explains the principles of a good experimental design.
---

## Introduction

Biologists design experiments everyday, but sometimes they don't really *think* about experiment design.

The basic principles of experiment design are listed below:

1.  Questions/goal of the experiment
2.  Comparison/control
3.  Replication
4.  Randomization
5.  Stratification/blocking
6.  Factorial experiments

## Experimental Design

Let's imagine a simple scenario:

> **Question**: Does salted drinking water affect blood pressure (BP) in mice?
>
> **Experiment**:
>
> 1.  Provide a mouse with water containing 1% NaCl.
> 2.  Wait 14 days.
> 3.  Measure BP.

### Comparison/Control

You need a *reference* group to see the *effect* of salted drinking water.

Common control group designs could be:

-   Compare BP in mice fed salt water to BP in mice fed plain water.
-   Compare BP in strain A mice fed salt water to BP in strain B mice fed salt water.

::: callout-note
Ideally, the experimental group is compared to *concurrent* controls (rather than to historical controls).
:::

### Replication

*Replicates* are needed to 1) reduce the effect of uncontrolled variation (increase precision), and to 2) quantify uncertainty.

In this scenario, 10 mouse per group would be a reasonable design.

::: callout-note
An estimate is of no value without some statement of the uncertainty in the estimate.
:::

### Randomization

Experimental subjects ('units') should be assigned to treatment groups *at random* to 1) avoid bias and 2) to control the role of chance.

::: callout-note
*At random* does NOT mean haphazardly.

It also allows the later use of probability theory, thus giving a solid foundation for statistical analysis.
:::

### Stratification/Blocking

Suppose that some BP measurements will be made in the morning, and some in the afternoon. If you anticipate a difference between morning and the afternoon - ensure that within each period, there are equal numbers of subjects in each treatment group (this is called *stratification*, or *blocking*); also, take account of the difference between periods in your analysis.

::: callout-note
Let's imagine we have 6 F mice, 6 M mice; half to be treated (T), half left untreated (C); we can only work with 6 mice per day. How to assign individuals to treatment groups, and to days?

-   Bad Design:

    | D1  |     | D2  |     |
    |-----|-----|-----|-----|
    | F-T | F-C | M-T | M-C |
    | F-T | F-C | M-T | M-C |
    | F-T | F-C | M-T | M-C |

-   Randomized Design:

    | D1  |     | D2  |     |
    |-----|-----|-----|-----|
    | M-T | F-C | M-T | F-C |
    | F-T | F-T | M-C | M-C |
    | F-T | M-T | F-C | M-C |

-   Stratified Design:

    | D1  |     | D2  |     |
    |-----|-----|-----|-----|
    | M-C | M-C | M-T | F-C |
    | M-T | F-T | F-C | M-T |
    | F-C | F-T | M-C | F-T |
:::

::: callout-tip
## Principles of Randomization and Stratification

-   If you can (and want to), *fix* a variable. (e.g., only use 8-week old M mice from a single strain.)
-   If you don't fix a variable, *stratify* it. (e.g., use 8 week and 12 week old M mice, and stratify them respect to age.)
-   If you can neither fix nor stratify a variable, *randomize* it.
:::

### Factorial Experiments

Suppose we are interested in the effect of both salt water and a high-fat diet on blood pressure. 

Ideally, we will look at *all 4 treatments in 1 experiment*; thus, we can 1) learn more (=is there any *interactive outcome*?). 2) make it more efficient compared to doing all single-factor experiments.

|             |     |               |
|:-----------:|:---:|:-------------:|
| Plain water |     |  Normal diet  |
|             |  x  |               |
| Salt water  |     | High-fat diet |

### Other Points to Consider

- **Blinding**: measurements made by people can be influenced by unconscious biases. Ideally, dissections and measurements should be made without knowledge of the treatment applied.

- **Internal controls**: it can be useful to use the subjects themselves as their own controls (e.g., consider the response after vs. before treatment) to increase precision.

- **Representativeness**: are the subjects/tissues you're studying really representative of the population you want to study? Ideally, your study material is a stratified random sample from the population of interest.

- **Power**: Experimental Design considerations (balanced designs) and sample size calculations are crucial, in particular w/ regards to your predictor of interest. 

## Credit

-   **140.615/616** Statistics for Lab Scientists I & II *by* Dr. Ingo Ruczinski

---

I decide to write my stats notes taken from those classes into easy-to-read articles and publish them, since I want to get an A in the stats class I'm taking this semester, practice typing *LaTex*, and have a quick reference whenever needed rather than search for 'how to perform ANOVA in R' by Google.

> The saying goes, *'学好数理化，走遍天下都不怕'（from Maths, Physics and Chemistry to anywhere in the world）* ;
>
> And the saying also goes *'基础不牢，地动山摇'（your life would suck if your STEM foundation sucks）*
