---
title: "Bookmarks for Biologists"
date: "2024-11-9"
categories: [biology, resources, EN]
---

# Online Database/Tools

-   [NCBI BLAST/Basic Local Alignment Search Tool](https://blast.ncbi.nlm.nih.gov/Blast.cgi): Just BLAST.

-   [Addgene](https://www.addgene.org/): A database for plasmids and vectors.

-   [CARD/The Comprehensive Antibiotic Resistance Database](https://card.mcmaster.ca/ontology/36319): A database for ARGs/ARBs.

-   [RCSB PDB/Protein Data Bank](https://www.rcsb.org/): A database for protein structures.

-   [The Jackson Laboratory](jax.org): A database for mouse models.

-   [AlphaFold](https://alphafold.ebi.ac.uk/): A database/tool for protein structures predicted by AlphaFold.

-   [TALEN Designer](https://tale-nt.cac.cornell.edu/): A TALEN vector designer.

-   [UCSF Chimera](https://zhuanlan.zhihu.com/p/427354394): A tool for protein 3D structure analysis.

-   [Benchling](https://www.benchling.com/): A cloud-based platform for biotech R&D. Similar to SnapGene.

-   [SignalP](https://services.healthtech.dtu.dk/service.php?SignalP-4.1): Predicts the presence and location of signal peptide cleavage sites in amino acid sequences from different organisms.

-   [Bioconductor](https://www.bioconductor.org/about/release-announcements/#release-announcements): A powerful R package for bioinformatics analysis.

-   [TimeTree: The Timescale of Life](http://www.timetree.org/): A tool for phylogenetic analysis (*for fun*).

-   [Vitascientific.com: Melting Temperature (Tm) Calculation](https://www.vitascientific.com/information/calculator)

-   [NCBI Primer Blast: Primer Designing Tool](https://www.ncbi.nlm.nih.gov/tools/primer-blast/)

-   [BioRender](https://app.biorender.com/gallery/illustrations): A tool to make scientific graphs.

-   [国家气象信息中心-中国气象数据网](http://data.cma.cn/)

-   [中国气象局国家气候中心](http://cmdp.ncc-cma.net/cn/index.htm)

# Blogs/Tips/Tutorials

## Molecular Cloning

-   [YouTube Tutorial: Choose Expression Vectors](https://www.youtube.com/watch?v=wOvpkJiVGhc)

-   [AAT Bioquest: Restriction Enzymes Cut Sizes Reference Table](https://www.aatbio.com/data-sets/restriction-enzymes-cut-sites-reference-table)

-   [Blog (CN): 双酶切](https://m.antpedia.com/news/2440075.html)

-   [Blog (CN): 蛋白标签_1](https://www.genewiz.com.cn/Public/Resources/zxzx/0027/)

-   [Blog (CN): 蛋白标签_2](http://www.360doc.com/content/16/0920/10/19913717_592204528.shtml)

-   [ResearchGate: 3xHA Linker](https://www.researchgate.net/post/What-is-the-best-linkers-for-3xHA-tag-Is-linkers-required-between-tags-and-or-between-tag-and-an-gene-of-interest)

-   [Blog (CN): 密码子优化](https://www.sohu.com/a/517081954_121124565)

-   [Blog (CN): 保护碱基_1](https://www.docin.com/p-71172519.html)

-   [Blog (CN): 保护碱基_2](https://www.jingege.wang/2020/11/03/%E5%90%84%E7%A7%8D%E9%85%B6%E5%88%87%E4%BD%8D%E7%82%B9%E7%9A%84%E4%BF%9D%E6%8A%A4%E7%A2%B1%E5%9F%BA/)

-   [Addgene: Primer Design](https://www.addgene.org/protocols/primer-design/)

-   [YouTube Tutorial: Primer Design using Benchling](https://www.youtube.com/watch?v=3vOSD7hA2nk)

-   [Blog (CN): 引物设计_知乎](https://zhuanlan.zhihu.com/p/22411347)

-   [ResearchGate: Universal Primers vs. Degenerate Primers](https://www.researchgate.net/post/Difference-between-Universal-Primers-and-Degenerate-Primers)

-   [BL21-DE3 Competent Cell Transformation_NEB](https://international.neb.com/protocols/0001/01/01/transformation-protocol-for-bl21-de3-competent-cells-c2527)

-   [Blog (CN): 质粒的转化](https://www.163.com/dy/article/FD2BK1N80517Q6RE.html)

-   [Plasmid Miniprep](https://cbs.umn.edu/hackett-lab/protocols/mini-prep)

-   [Alkaline Lysis](https://bitesizebio.com/180/the-basics-how-alkaline-lysis-works/)

-   [Guide of Analyzing Gel Electrophoresis Results](https://geneticeducation.co.in/a-complete-guide-for-analysing-and-interpreting-gel-electrophoresis-results/)

-   [Causes of Faint Bands in Gel Electrophoresis](https://findanyanswer.com/what-causes-faint-bands-in-gel-electrophoresis)

## Protein Analysis

-   [Addgene: Western Blot](https://www.addgene.org/protocols/western-blot/)

-   [Absorption Spectroscopy](https://www.dur.ac.uk/chemistry/outreach/spectroscopy_in_a_suitcase/absorption_spectroscopy/)

-   [Ninhydrin Reaction Mechanism](https://iubmb.onlinelibrary.wiley.com/doi/pdf/10.1016/0307-4412(78)90153-X)

## Sequencing

### Sanger Sequencing

-   [Sequencing Chromatograms Interpretation](https://brcf.medicine.umich.edu/cores/advanced-genomics/faqs/sanger-sequencing-faqs/interpretation-of-sequencing-chromatograms/)

-   [DNA Barcoding: Promise and Pitfalls](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0020354)

### NGS/Next-Generation Sequencing

-   [Genomic Data Science_Coursera](https://www.coursera.org/specializations/genomic-data-science)

-   [Spacer DNA](https://groups.molbiosci.northwestern.edu/holmgren/Glossary/Definitions/Def-S/spacer_DNA.html)

-   [DADA2 Tutorial](https://benjjneb.github.io/dada2/tutorial.html)

-   [Blog (CN): DADA2 中文教程](https://blog.csdn.net/woodcorpse/article/details/86773312)

-   [16s RefSeq Records Processing and Curation](https://www-ncbi-nlm-nih-gov.proxy.lib.duke.edu/refseq/targetedloci/16S_process/)

-   [Bioinformatics_Coursera](https://www.coursera.org/specializations/bioinformatics)

-   [Bioinformatic Methods I_Coursera](https://www.coursera.org/learn/bioinformatics-methods-1)

-   [Algorithms for DNA Sequencing_Coursera](https://www.coursera.org/learn/dna-sequencing)

-   [phyloseq: R package for learning microbiome](https://joey711.github.io/phyloseq/)

## Quantitative PCR

-   [Blog (CN): 提升扩增效率_1](https://www.genewiz.com.cn/zh-cn/public/resources/zxzx/0035)

-   [Blog (CN): 提升扩增效率_2](http://www.tkgeneclub.com/tkgeneclub/news_detail/newsId=71.html)

-   [CRAN: Analysis of qPCR Data, R package](https://cran.r-project.org/web/packages/pcr/vignettes/qpcr_analysis.html)

-   [Publish qPCR data with bar graph_ggplot2](https://www.researchgate.net/post/How-do-I-publish-qPCR-data-in-a-bar-graph)

## CRISPR

-   [GPP sgRNA Designer](https://portals.broadinstitute.org/gpp/public/analysistools/sgrna-design)

-   [GenScript gRNA Design Tool](https://www.genscript.com/gRNA-design-tool.html)

-   [Addgene CRISPR](https://www.addgene.org/guides/crispr/)

-   [Thermofisher CRISPR](https://www.thermofisher.com/cn/zh/home/lifescience/genome-editing/geneart-crispr.html)

-   [Synthego](https://www.synthego.com/)

## Pharmacogenomics

-   [PolyPhen-2](http://genetics.bwh.harvard.edu/pph2/): A tool for prediction of functional effects of human nsSNPs.

-   [PROVEAN](http://provean.jcvi.org/index.php): A database for prediction of protein functional changes.

-   [NCBI-dbSNP](https://www.ncbi.nlm.nih.gov/snp/): A mutation database.

-   [PharmVar/Pharmacogene Variation Consortium](https://www.pharmvar.org/genes): A database for drug-related genes.

-   [CPIC/Clinical Pharmacogenetics Implementation Consortium](https://cpicpgx.org/): A database for drug-related genes.

-   [PharmGKB](https://www.pharmgkb.org/): A database for drug-related genes.

## Drug Crystallization

-   [XRPD/X-Ray Powder Diffraction](http://www.xrpd.eu/)

-   [Blog (CN): XRPD:布拉格定律](https://highscope.ch.ntu.edu.tw/wordpress/?p=41141)

-   [DSC/Differential Scanning Calorimetry](https://en.wikipedia.org/wiki/Differential_scanning_calorimetry)

-   [Blog (CN): 热重分析](https://zh.wikipedia.org/wiki/%E7%86%B1%E9%87%8D%E5%88%86%E6%9E%90)

# Others

-   [讯飞听见](https://www.iflyrec.com/): Transcribe audios into words.

-   [Reddit subreddit/labrats](https://www.reddit.com/r/labrats/): A forum for biology-related discussions.
